[2025-03-17T07:05:18.186+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T07:05:18.207+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_b scheduled__2025-03-14T00:00:00+00:00 [queued]>
[2025-03-17T07:05:18.217+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_b scheduled__2025-03-14T00:00:00+00:00 [queued]>
[2025-03-17T07:05:18.218+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-17T07:05:18.232+0000] {taskinstance.py:2889} INFO - Executing <Task(ExternalPythonOperator): ext_py_b> on 2025-03-14 00:00:00+00:00
[2025-03-17T07:05:18.242+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=139) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-17T07:05:18.243+0000] {standard_task_runner.py:72} INFO - Started process 145 to run task
[2025-03-17T07:05:18.243+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'example_branch_operator', 'ext_py_b', 'scheduled__2025-03-14T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator.py', '--cfg-path', '/tmp/tmprgruduu0']
[2025-03-17T07:05:18.244+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask ext_py_b
[2025-03-17T07:05:18.282+0000] {task_command.py:467} INFO - Running <TaskInstance: example_branch_operator.ext_py_b scheduled__2025-03-14T00:00:00+00:00 [running]> on host 758401fd595f
[2025-03-17T07:05:18.355+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_operator' AIRFLOW_CTX_TASK_ID='ext_py_b' AIRFLOW_CTX_EXECUTION_DATE='2025-03-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-14T00:00:00+00:00'
[2025-03-17T07:05:18.357+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-17T07:05:18.357+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-17T07:05:18.357+0000] {logging_mixin.py:190} INFO - Current task name:ext_py_b state:running start_date:2025-03-17 07:05:18.207722+00:00
[2025-03-17T07:05:18.358+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_operator and current dag run status:running
[2025-03-17T07:05:18.358+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-17T07:05:18.641+0000] {baseoperator.py:416} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-17T07:05:18.678+0000] {process_utils.py:186} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-call6qnn4g0v/script.py /tmp/venv-call6qnn4g0v/script.in /tmp/venv-call6qnn4g0v/script.out /tmp/venv-call6qnn4g0v/string_args.txt /tmp/venv-call6qnn4g0v/termination.log
[2025-03-17T07:05:18.679+0000] {process_utils.py:190} INFO - Output:
[2025-03-17T07:05:20.006+0000] {process_utils.py:194} INFO - /home/***/.local/lib/python3.12/site-packages/***/configuration.py:859 FutureWarning: section/key [core/sql_alchemy_conn] has been deprecated, you should use[database/sql_alchemy_conn] instead. Please update your `conf.get*` call to use the new name
[2025-03-17T07:05:20.970+0000] {process_utils.py:194} INFO - Hello World from external Python
[2025-03-17T07:05:21.279+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-17T07:05:21.288+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-17T07:05:21.289+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=example_branch_operator, task_id=ext_py_b, run_id=scheduled__2025-03-14T00:00:00+00:00, execution_date=20250314T000000, start_date=20250317T070518, end_date=20250317T070521
[2025-03-17T07:05:21.298+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-17T07:05:21.298+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-17T07:05:21.299+0000] {logging_mixin.py:190} INFO - Dag name:example_branch_operator queued_at:2025-03-17 07:05:01.824396+00:00
[2025-03-17T07:05:21.299+0000] {logging_mixin.py:190} INFO - Task hostname:758401fd595f operator:ExternalPythonOperator
[2025-03-17T07:05:21.334+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-17T07:05:21.353+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T07:05:21.355+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
